import Head from 'next/head'
import styles from '../../styles/Login.module.css'

export default function Cars() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Cars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* ["name", "brand", "model", "photo", "price"] */}
      <main className={styles.container_login}>
        <div className={styles.login}>
            <input placeholder='name'/>
            <input placeholder='brand'/>
            <input placeholder='model'/>
            <input type='file' />
            <input placeholder='price'/>
        </div>
        <div className={styles.btns}>
          <button className={styles.btn_save}>save</button>
          <button className={styles.btn_delete}>delete</button>
        </div>
      </main>
    </div>
  )
}
