import Head from 'next/head'
import { useEffect, useState } from 'react';
import axios from 'axios'

import styles from '../../styles/Home.module.css'
import Image from 'next/image';
import { useRouter } from 'next/router';
import Link from 'next/link';

export default function Admin() {
  const [cars, setCars ] = useState([])

  const route = useRouter()

  useEffect(() => {
  
    axios.get(`${process.env.API_URL}/cars/?me=True`,{
      headers: {
        Authorization: `Bearer ${window.localStorage.getItem('token')}`
      }
    })
    .then(response => {
      const status = response.status
      console.log(response)
      if (status == 200) {
        setCars(response.data)
      }       
    }).catch(e => {
      console.log("error", e)
      if (e.response?.status == 401) {
        route.push('/')
      }
    });
  }, [])

  const handleNewCar = () => {
    route.push('/admin/cars')
  }

  const handleLogUot = () => {
    window.localStorage.removeItem('token')
    route.push('/')
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <div className={styles.list_cars}>
            {cars.map(car => {
                return <Link href={`/admin/cars?id=${car.slug}`}>
                  <div className={styles.car_content}>
                    <strong>{car.name}</strong>
                    <div className={styles.car_grid}>
                      <p>marca: {car.brand}</p>
                      <p>modelo: {car.model}</p>
                      <p>slug: {car.slug}</p>
                      <p>preco: {car.price}</p>
                      {/* <Image src={car?.photo} width='100' height='100' /> */}
                    </div>
                  </div>                
                </Link>
            })}
        </div>
      </main>
      <footer className={styles.footer}>
        <button onClick={handleNewCar} className={styles.btn_new}>novo carro</button>
        <button onClick={handleLogUot} className={styles.btn_cancel}>loguot</button>
      </footer>
    </div>
  )
}
