import Head from 'next/head'

import styles from '../styles/Home.module.css'

import { useEffect, useState } from 'react';
import axios from 'axios'
import { useRouter } from 'next/router';
import Link from 'next/link';

export default function Home() {
  const [cars, setCars] = useState([])
  const route = useRouter()

  useEffect(() => {
  
    axios.get(`${process.env.API_URL}/cars/`)
    .then(response => {
      const status = response.status
      console.log(response)
      if (status == 200) {
        setCars(response.data)
      }       
    }).catch(e => {
      console.log("error", e)
      if (e.response?.status == 401) {
        route.push('/')
      }
    });
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <div className={styles.btn_sign} >
          <Link href='/login'>SignIn</Link>
        </div>
        <div className={styles.btn_sign} >
          <Link href='/signup'>SignUp</Link>
        </div>
        <div className={styles.btn_sign} >
          <Link href='/admin'>admin</Link>
        </div>
      </header>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Prova Josué 
        </h1>

        <p className={styles.description}>
          Verzel
        </p>

        <div className={styles.grid}>
          {cars.map(car => {
            return <a href="https://nextjs.org/docs" className={styles.card}>
              <h2>{car.name} &rarr;</h2>
              <p>marca: {car.brand}</p>
              <p>modelo: {car.model}</p>
              <p>slug: {car.slug}</p>
              <p>preco: {car.price}</p>
            </a>
          })}
        </div>
      </main>
    </div>
  )
}
