import Head from 'next/head'
import styles from '../styles/Login.module.css'

export default function Login() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container_login}>
        <div className={styles.login}>
            <input placeholder='e-mail'/>
            <input placeholder='password'/>
            <button>login</button>
        </div>
      </main>
    </div>
  )
}
